### ISSUE TITLE
Missing oh-my-zsh.sh

### ISSUE THREAD

**Issue by p4rkrs** [AndreasBackx/dotfiles#1]
Hi,

the file oh-my-zsh.zsh that you are mentionning in the .zshrc doesn't exist on the repo.

**Comment by AndreasBackx** [comment]
The folder `~/.oh-my-zsh` is actually from the [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) zsh framework. I've only included the subfolder `custom` because that contains specific files for my configuration. Install oh-my-zsh and it should be there.

Feel free to ask some more questions if you've got some. I'm closing the issue already because it's not intended to be imported here.
