### ISSUE TITLE
spotifyctl wanting spotify_username and other problems

### ISSUE THREAD

**Issue by Mladia** [AndreasBackx/dotfiles#2]
I saw your post on /r/unixporn and wanted to try your script.
Firstly I noticed that it does not work if `SPOTIFY_USERNAME` is not set. With that in mind, `spotifyctl status` works!

Secondly, I tried `save-remove` and I get this error:
```
 ➜ ./spotifyctl save-remove
Traceback (most recent call last):
  File "./spotifyctl", line 303, in <module>
    cli()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./spotifyctl", line 299, in save_remove
    spotify.send_to_server(Spotify.SAVE_REMOVE)
  File "./spotifyctl", line 123, in send_to_server
    sock.connect(server_address)
ConnectionRefusedError: [Errno 111] Connection refused

```
I am using arch with all newest updates.

**Comment by AndreasBackx** [comment]
I keep a `.secrets` file somewhere with some secret keys for Spotify authentication along with other stuff. To avoid having to login every time, [see the Spotipy's documentation](https://spotipy.readthedocs.io/en/latest/#authorization-code-flow) as it describes how you can remain logged in and how `prompt_for_user_token` works, which is used in spotifyctl.

Regarding your error, spotifyctl has 2 components: it has a server and a client. Because it's a simple script, they're kept together as they share code. When running `spotifyctl status`, it'll output the status of Spotify as it receives events over the dbus. This is a long running process and it will at the same time start a server on a socket (see `Spotify.monitor`). `spotifyctl save-remove` simply sends a message to the server telling it to either save or remove the song from the library which is why it says "Connection refused" as you don't have the status command running in the background.

**Comment by Mladia** [comment]
I see. I've got it working now.
